### ISSUE TITLE
Delete unused pacman sensor blocks

### ISSUE THREAD

**Issue by schrum2** [schrum2/MsPacManEntry#3]
Look carefully at your InputOutputMediator and delete the Pacman sensor blocks that you know you are not using. The main issue to be careful of here is that many sensor blocks extend other sensor blocks, so be sure to thoroughly check what you are actually using.

In order to make it easy to back track any mistakes, do a commit after each deletion so we can do targeted reverts if necessary

**Comment by Squillyprice01** [comment]
A good chunk of this is done now
